name: Publish library to repository
on:
  push:
    branches:
      - main
      - master

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build jar
        run: ./gradlew clean build publish
        env:
          GIT_PUBLISH_USER: ${{ secrets.GIT_PUBLISH_USER  }}
          GIT_PUBLISH_PASSWORD: ${{ secrets.GIT_PUBLISH_PASSWORD }}
